# Generated by Django 4.2 on 2024-05-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tumodelo',
            old_name='casilla1',
            new_name='opcion1',
        ),
        migrations.AddField(
            model_name='tumodelo',
            name='opcion2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tumodelo',
            name='opcion3',
            field=models.BooleanField(default=False),
        ),
    ]
